--- #YAML:1.0
name:               LWP-UserAgent-Cached
version:            0.03
abstract:           LWP::UserAgent with simple caching mechanism
author:
    - Oleg G <oleg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.52
build_requires:
    File::Temp:           0
    Test::Mock::LWP::Dispatch:  0.02
    Test::More:           0.88
requires:
    LWP::UserAgent:  0
resources:
    repository:  https://github.com/olegwtf/p5-LWP-UserAgent-Cached
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
